project:
  type: website
  output-dir: docs	

website:
  title: "My site"
  site-url: https://gustavo-perez-arrobo.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - Research.qmd
      - Teaching.qmd
      - Information.qmd
  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

