---
title: "Research"
format: html
---

**Publications:**

-   Del gabinete a la papeleta: ministros y ministras como candidatos presidenciales. 2024. *Revista Española De Ciencia Política 65* : 113–147. with Sergio Huertas and Alejandro Olivares ([Link](https://recyt.fecyt.es/index.php/recp/article/view/96235))

-   Crisis económica e \[in\]estabilidad política: la política latinoamericana frente a la Gran Depresión de 1930. 2022. *Lecturas De Economía 97* : 181–216. with Carolina Curvale. ([Link](https://revistas.udea.edu.co/index.php/lecturasdeeconomia/article/view/346665?articlesBySimilarityPage=6))

-   Documentation Requirements and Open Access in Political Science Journals. 2021. *Revista de Ciencia Política 41*, 3: 477-495. with Carolina Curvale ([Link](https://revistacienciapolitica.uc.cl/index.php/rcp/article/view/39539))

-   Is There Such a Thing as Latin America. 2018. *Política. Revista de Ciencia Política 56*, 1: 61-87. with Carolina Curvale ([Link](https://revistapolitica.uchile.cl/index.php/RP/article/view/58134))

**Working Papers:**

-   Why Do Some Governments Lose? Institutional Capacity in Oil Spill Lawsuits. (*submitted for review*) [Paper](https://github.com/Gustavo-Perez-Arrobo/gustavo-perez-arrobo.github.io/blob/main/files/Oil%20Spills%20and%20Lawsuits.pdf?raw=true)

<!-- -->

-   Democracy Measures and Democratic Backsliding: Latin America in Comparative Perspective. [Paper](https://github.com/Gustavo-Perez-Arrobo/gustavo-perez-arrobo.github.io/blob/main/files/Democracy%20and%20Backsliding%20in%20LA.pdf?raw=true)

**Work in Progress:**

-   Compatible or at Odds? Protesters’ Attitudes Toward the Political System in Latin America (with Carew Boulding and V. Ximena Velasco-Guachalla).

-    Mixed-Method application with panel data: the selection of cases.

-   Economic Shocks and Respect for Political Institutions in Latin America: An Explanation from Protester’s Behavior.

-   Replacements and Amendments: a Constitutional Change Comparison in Latin America.

-   Corruption and Rulers’ Approval: a worldwide approach (with Santiago Basabe-Serrano).

**Articles in Press:**

-    “¿Promesas rotas? Cooperación, estrategia y dilemas de la derecha”. 2022. El Desconcierto (with Gastón Alvear) ([Link](https://eldesconcierto.cl/2022/08/21/promesas-rotas-cooperacion-estrategia-y-dilemas-de-la-derecha))
