---
title: "Teaching"
---

**Instructor:**

-   Applied Political Science Research - PSCI 3075, Spring 2025; Fall 2025 – University of Colorado Boulder

-   Comparative Political Economy - PSCI 3092, Summer 2025 – University of Colorado Boulder

-   Introduction to Comparative Politics - PSCI 2012, Summer 2024 – University of Colorado Boulder

-   Methods Lab Coordinator, Fall 2023, Spring 2024 - University of Colorado Boulder.

-   Introduction to Data Analysis using STATA, March 2019 – FLACSO, Ecuador

-   Quantitative Methods in Social Sciences, December 2018 – AECIP

-   Introduction to Game Theory in Social Sciences, June 2018 – Universidad de los Hemisferios

**Teaching Assistant:**

-   Quantitative Research Methods - PSCI 2075, Fall 2022, 2024; Spring 2023; – University of Colorado Boulder

-   Introduction to Comparative Politics - PSCI 2012, Spring 2022 – University of Colorado Boulder

-   Revolution and Political Violence - PSCI 3062, Fall 2021 – University of Colorado Boulder

-   Quantitative Methods in Comparative Politics, May-July 2018 – FLACSO, Ecuador
